agent:
  input:
    procstat:
      process:
        dockerd:
          exe: dockerd
    docker:
      # Input plugin configuration
      endpoint: unix:///var/run/docker.sock
      timeout: 5
      perdevice: true
      total: false
      gather_services: false
      container_name_exclude: [ "*" ]
      # Measurement filtering
      namepass: [ "docker", "docker_swarm" ]
