apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: mol.local
      protocol: layer2
      addresses:
      - 192.168.0.220-192.168.0.235
